name: Test python application

on:
  push:
    branches: [ main, stable ]
  pull_request:
    branches: [ main, stable ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.4.2
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest

